name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Reconstruct and Build
        run: |
          cd my_video_player
          
          # 1. 彻底清理旧缓存
          flutter clean
          
          # 2. 强制重新生成 Android 文件（确保 pubspec.yaml 生效）
          flutter create . --platforms=android
          
          # 3. 重新获取插件
          flutter pub get
          
          # 4. 这里的关键：给 gradlew 运行权限，防止服务器拒绝执行
          chmod +x android/gradlew
          
          # 5. 执行打包，并跳过版本校验
          flutter build apk --release --no-tree-shake-icons --android-skip-build-dependency-validation
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-private-player
          path: my_video_player/build/app/outputs/flutter-apk/app-release.apk