name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Reconstruct and Build
        run: |
          # 1. 进入存放 main.dart 的目录
          cd my_video_player
          
          # 2. 暴力删除已经损坏的旧 android 文件夹
          rm -rf android
          
          # 3. 原地重建一个完美的安卓外壳 (这会生成全新的 Gradle 和 kts 文件)
          flutter create . --platforms=android
          
          # 4. 获取依赖
          flutter pub get
          
          # 5. 执行正式打包
          flutter build apk --release --no-tree-shake-icons
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-private-player
          path: my_video_player/build/app/outputs/flutter-apk/app-release.apk